services:
  # Broker wiadomości RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: library_rabbitmq
    ports:
      - "5672:5672"   # Port komunikacyjny AMQP
      - "15672:15672" # Panel administracyjny UI
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Instancja bazy danych MongoDB
  mongodb:
    image: mongo:8.3.2
    container_name: library_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db # Wolumen do trzymania danych
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: