# Aplikacja LibraryService
server.port=8080
spring.application.name=LibraryService

# Baza danych dla LibraryService - /library_db
spring.data.mongodb.uri=mongodb://localhost:27017/library_db

# Współdzielony sekret JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970