# Aplikacja LibraryService
server.port=8080
spring.application.name=LibraryService
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Baza danych dla LibraryService - /library_db
spring.data.mongodb.uri=mongodb://localhost:27017/library_db
jwt.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzcrqyE6EYH42G8aqwstISdRbKYyf1hUivm3vczJaW91+KqjMnSliLr0JshvzcCH5bKiZcnMqJtVu/wfjSiU8RxRhPMyMrDzDNESFwVDeaVql3iaNtCwUpc9poMj2iLBjlx5Iaey8dn5nbHYWhU1fo7Rb01Pr2XlzWeV5/cvibo1oeLBUfmsfLpjtTPvyf2psXssrvLq8oxXyzmkgG2wcexL0R+i7pE7XrhTUGsEhP5l0uvtYJu34AmqTkoT/dx+1CiV9PehblhkvyTo8SeQ4PT0QLR4jyNnix92RLm6sJ/p5BUuNpD9Cuw3AT3d7RdOs+sObZRTJh9uxTaZZ7iChKwIDAQAB
management.endpoints.web.exposure.include=health,prometheus,metrics
mongock.migration-scan-package=pl.lodz.p.library.migrations
management.endpoint.health.show-details=always
spring.data.mongodb.auto-index-creation=true
jwt.secret=twoj-bardzo-dlugi-i-bezpieczny-sekret-hmac-dla-user-service