spring.application.name=LibraryWEB
library.rest.url=localhost:8082
server.port=8081
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.thymeleaf.encoding=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true